### ISSUE TITLE
Update testing framework

### ISSUE THREAD

**Issue by sidneymau** [PFLeget/treegp#7]
The current `treegp` testing framework is based on nose, which [appears to be defunct](https://nose.readthedocs.io/en/latest/index.html#note-to-users). There are several viable alternatives; notably,
- [nose2](https://docs.nose2.io/en/latest/)
- [pytest](https://docs.pytest.org/en/latest/)

I would suggest moving to using pytest (which should be fairly straightforward). This is also noted [here](https://github.com/PFLeget/treegp/pull/6#issuecomment-898789391).

**Comment by PFLeget** [comment]
Closing this issue as the workflow of GitHub action was merged and also now is triggered while a pull request is done.
